// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: api/bus/v1/bus.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateBusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateBusRequest) Reset() {
	*x = CreateBusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_bus_v1_bus_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBusRequest) ProtoMessage() {}

func (x *CreateBusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_bus_v1_bus_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBusRequest.ProtoReflect.Descriptor instead.
func (*CreateBusRequest) Descriptor() ([]byte, []int) {
	return file_api_bus_v1_bus_proto_rawDescGZIP(), []int{0}
}

type CreateBusReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateBusReply) Reset() {
	*x = CreateBusReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_bus_v1_bus_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBusReply) ProtoMessage() {}

func (x *CreateBusReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_bus_v1_bus_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBusReply.ProtoReflect.Descriptor instead.
func (*CreateBusReply) Descriptor() ([]byte, []int) {
	return file_api_bus_v1_bus_proto_rawDescGZIP(), []int{1}
}

type UpdateBusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateBusRequest) Reset() {
	*x = UpdateBusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_bus_v1_bus_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBusRequest) ProtoMessage() {}

func (x *UpdateBusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_bus_v1_bus_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBusRequest.ProtoReflect.Descriptor instead.
func (*UpdateBusRequest) Descriptor() ([]byte, []int) {
	return file_api_bus_v1_bus_proto_rawDescGZIP(), []int{2}
}

type UpdateBusReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateBusReply) Reset() {
	*x = UpdateBusReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_bus_v1_bus_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBusReply) ProtoMessage() {}

func (x *UpdateBusReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_bus_v1_bus_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBusReply.ProtoReflect.Descriptor instead.
func (*UpdateBusReply) Descriptor() ([]byte, []int) {
	return file_api_bus_v1_bus_proto_rawDescGZIP(), []int{3}
}

type DeleteBusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteBusRequest) Reset() {
	*x = DeleteBusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_bus_v1_bus_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBusRequest) ProtoMessage() {}

func (x *DeleteBusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_bus_v1_bus_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBusRequest.ProtoReflect.Descriptor instead.
func (*DeleteBusRequest) Descriptor() ([]byte, []int) {
	return file_api_bus_v1_bus_proto_rawDescGZIP(), []int{4}
}

type DeleteBusReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteBusReply) Reset() {
	*x = DeleteBusReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_bus_v1_bus_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBusReply) ProtoMessage() {}

func (x *DeleteBusReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_bus_v1_bus_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBusReply.ProtoReflect.Descriptor instead.
func (*DeleteBusReply) Descriptor() ([]byte, []int) {
	return file_api_bus_v1_bus_proto_rawDescGZIP(), []int{5}
}

type GetBusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetBusRequest) Reset() {
	*x = GetBusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_bus_v1_bus_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBusRequest) ProtoMessage() {}

func (x *GetBusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_bus_v1_bus_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBusRequest.ProtoReflect.Descriptor instead.
func (*GetBusRequest) Descriptor() ([]byte, []int) {
	return file_api_bus_v1_bus_proto_rawDescGZIP(), []int{6}
}

type GetBusReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetBusReply) Reset() {
	*x = GetBusReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_bus_v1_bus_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBusReply) ProtoMessage() {}

func (x *GetBusReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_bus_v1_bus_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBusReply.ProtoReflect.Descriptor instead.
func (*GetBusReply) Descriptor() ([]byte, []int) {
	return file_api_bus_v1_bus_proto_rawDescGZIP(), []int{7}
}

type ListBusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListBusRequest) Reset() {
	*x = ListBusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_bus_v1_bus_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBusRequest) ProtoMessage() {}

func (x *ListBusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_bus_v1_bus_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBusRequest.ProtoReflect.Descriptor instead.
func (*ListBusRequest) Descriptor() ([]byte, []int) {
	return file_api_bus_v1_bus_proto_rawDescGZIP(), []int{8}
}

type ListBusReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListBusReply) Reset() {
	*x = ListBusReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_bus_v1_bus_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBusReply) ProtoMessage() {}

func (x *ListBusReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_bus_v1_bus_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBusReply.ProtoReflect.Descriptor instead.
func (*ListBusReply) Descriptor() ([]byte, []int) {
	return file_api_bus_v1_bus_proto_rawDescGZIP(), []int{9}
}

var File_api_bus_v1_bus_proto protoreflect.FileDescriptor

var file_api_bus_v1_bus_proto_rawDesc = []byte{
	0x0a, 0x14, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x75, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x62, 0x75, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x75, 0x73, 0x2e,
	0x76, 0x31, 0x22, 0x12, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x75, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x10, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x42, 0x75, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x12, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x42, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x10, 0x0a, 0x0e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x75, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x12,
	0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x10, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x75, 0x73, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x0f, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x42, 0x75, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0d, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x42, 0x75, 0x73, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x10, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x75, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x75,
	0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0xd9, 0x02, 0x0a, 0x03, 0x42, 0x75, 0x73, 0x12, 0x45,
	0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x75, 0x73, 0x12, 0x1c, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x62, 0x75, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42,
	0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x62, 0x75, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x75, 0x73,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x45, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42,
	0x75, 0x73, 0x12, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x75, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x75, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x42, 0x75, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x45, 0x0a, 0x09,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x75, 0x73, 0x12, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x62, 0x75, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x75, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x75,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x75, 0x73, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x3c, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x42, 0x75, 0x73, 0x12, 0x19, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x62, 0x75, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x75,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x62,
	0x75, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x75, 0x73, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x3f, 0x0a, 0x07, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x75, 0x73, 0x12, 0x1a, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x62, 0x75, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x75,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x62,
	0x75, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x75, 0x73, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x42, 0x29, 0x0a, 0x0a, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x75, 0x73, 0x2e, 0x76, 0x31,
	0x50, 0x01, 0x5a, 0x19, 0x62, 0x75, 0x73, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x62, 0x75, 0x73, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_bus_v1_bus_proto_rawDescOnce sync.Once
	file_api_bus_v1_bus_proto_rawDescData = file_api_bus_v1_bus_proto_rawDesc
)

func file_api_bus_v1_bus_proto_rawDescGZIP() []byte {
	file_api_bus_v1_bus_proto_rawDescOnce.Do(func() {
		file_api_bus_v1_bus_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_bus_v1_bus_proto_rawDescData)
	})
	return file_api_bus_v1_bus_proto_rawDescData
}

var file_api_bus_v1_bus_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_bus_v1_bus_proto_goTypes = []interface{}{
	(*CreateBusRequest)(nil), // 0: api.bus.v1.CreateBusRequest
	(*CreateBusReply)(nil),   // 1: api.bus.v1.CreateBusReply
	(*UpdateBusRequest)(nil), // 2: api.bus.v1.UpdateBusRequest
	(*UpdateBusReply)(nil),   // 3: api.bus.v1.UpdateBusReply
	(*DeleteBusRequest)(nil), // 4: api.bus.v1.DeleteBusRequest
	(*DeleteBusReply)(nil),   // 5: api.bus.v1.DeleteBusReply
	(*GetBusRequest)(nil),    // 6: api.bus.v1.GetBusRequest
	(*GetBusReply)(nil),      // 7: api.bus.v1.GetBusReply
	(*ListBusRequest)(nil),   // 8: api.bus.v1.ListBusRequest
	(*ListBusReply)(nil),     // 9: api.bus.v1.ListBusReply
}
var file_api_bus_v1_bus_proto_depIdxs = []int32{
	0, // 0: api.bus.v1.Bus.CreateBus:input_type -> api.bus.v1.CreateBusRequest
	2, // 1: api.bus.v1.Bus.UpdateBus:input_type -> api.bus.v1.UpdateBusRequest
	4, // 2: api.bus.v1.Bus.DeleteBus:input_type -> api.bus.v1.DeleteBusRequest
	6, // 3: api.bus.v1.Bus.GetBus:input_type -> api.bus.v1.GetBusRequest
	8, // 4: api.bus.v1.Bus.ListBus:input_type -> api.bus.v1.ListBusRequest
	1, // 5: api.bus.v1.Bus.CreateBus:output_type -> api.bus.v1.CreateBusReply
	3, // 6: api.bus.v1.Bus.UpdateBus:output_type -> api.bus.v1.UpdateBusReply
	5, // 7: api.bus.v1.Bus.DeleteBus:output_type -> api.bus.v1.DeleteBusReply
	7, // 8: api.bus.v1.Bus.GetBus:output_type -> api.bus.v1.GetBusReply
	9, // 9: api.bus.v1.Bus.ListBus:output_type -> api.bus.v1.ListBusReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_bus_v1_bus_proto_init() }
func file_api_bus_v1_bus_proto_init() {
	if File_api_bus_v1_bus_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_bus_v1_bus_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_bus_v1_bus_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBusReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_bus_v1_bus_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateBusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_bus_v1_bus_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateBusReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_bus_v1_bus_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_bus_v1_bus_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBusReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_bus_v1_bus_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_bus_v1_bus_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBusReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_bus_v1_bus_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_bus_v1_bus_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBusReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_bus_v1_bus_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_bus_v1_bus_proto_goTypes,
		DependencyIndexes: file_api_bus_v1_bus_proto_depIdxs,
		MessageInfos:      file_api_bus_v1_bus_proto_msgTypes,
	}.Build()
	File_api_bus_v1_bus_proto = out.File
	file_api_bus_v1_bus_proto_rawDesc = nil
	file_api_bus_v1_bus_proto_goTypes = nil
	file_api_bus_v1_bus_proto_depIdxs = nil
}
