basePath: /
definitions:
  bus-service_internal_biz.Bus:
    properties:
      driver:
        $ref: '#/definitions/bus-service_internal_biz.BusUser'
      id:
        type: integer
      number:
        type: string
      route:
        $ref: '#/definitions/bus-service_internal_biz.Route'
      routeID:
        type: integer
      status:
        type: string
    type: object
  bus-service_internal_biz.BusUser:
    properties:
      email:
        type: string
      firstName:
        type: string
      id:
        type: string
      lastName:
        type: string
      username:
        type: string
    type: object
  bus-service_internal_biz.Route:
    properties:
      id:
        type: integer
      number:
        type: string
      path:
        type: string
      stations:
        items:
          $ref: '#/definitions/bus-service_internal_biz.Stations'
        type: array
    type: object
  bus-service_internal_biz.Stations:
    properties:
      id:
        type: integer
      lat:
        type: number
      lon:
        type: number
      name:
        type: string
      routes:
        items:
          $ref: '#/definitions/bus-service_internal_biz.Route'
        type: array
    type: object
  internal_route.BusDTO:
    properties:
      driverID:
        type: string
      number:
        type: string
      routeID:
        type: integer
      status:
        type: string
    required:
    - driverID
    - number
    - routeID
    - status
    type: object
  internal_route.ListBuses:
    properties:
      buses:
        items:
          $ref: '#/definitions/bus-service_internal_biz.Bus'
        type: array
      count:
        type: integer
    type: object
  internal_route.RouteDTO:
    properties:
      number:
        type: string
      stations:
        description: Path     string
        items:
          $ref: '#/definitions/internal_route.StationDTO'
        type: array
    required:
    - number
    - stations
    type: object
  internal_route.StationDTO:
    properties:
      id:
        type: integer
      lat:
        type: number
      lon:
        type: number
      name:
        type: string
    required:
    - lat
    - lon
    - name
    type: object
host: bus.e-bus.site
info:
  contact:
    email: suro@hyneo.ru
    name: Suro
    url: https://t.me/suronek
  description: This is documentation api for backend
  title: Bus Service Swagger API
  version: "1.0"
paths:
  /bus/:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_route.ListBuses'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: List buses
      tags:
      - bus
    post:
      consumes:
      - application/json
      parameters:
      - description: dto
        in: body
        name: dto
        required: true
        schema:
          $ref: '#/definitions/internal_route.BusDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Create bus
      tags:
      - bus
  /bus/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Bus ID
        format: uint64
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Delete bus
      tags:
      - bus
    get:
      consumes:
      - application/json
      parameters:
      - description: Bus ID
        format: uint64
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/bus-service_internal_biz.Bus'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get bus by id
      tags:
      - bus
    put:
      consumes:
      - application/json
      parameters:
      - description: Bus ID
        format: uint64
        in: path
        name: id
        required: true
        type: integer
      - description: dto
        in: body
        name: dto
        required: true
        schema:
          $ref: '#/definitions/internal_route.BusDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Update bus
      tags:
      - bus
  /route/:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/bus-service_internal_biz.Route'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: List route
      tags:
      - route
    post:
      consumes:
      - application/json
      parameters:
      - description: dto
        in: body
        name: dto
        required: true
        schema:
          $ref: '#/definitions/internal_route.RouteDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Create route
      tags:
      - route
  /route/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Route ID
        format: uint64
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Delete route
      tags:
      - route
    get:
      consumes:
      - application/json
      parameters:
      - description: Route ID
        format: uint64
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/bus-service_internal_biz.Route'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get route
      tags:
      - route
    put:
      consumes:
      - application/json
      parameters:
      - description: Route ID
        format: uint64
        in: path
        name: id
        required: true
        type: integer
      - description: dto
        in: body
        name: dto
        required: true
        schema:
          $ref: '#/definitions/internal_route.RouteDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Update route
      tags:
      - route
securityDefinitions:
  authorization:
    in: header
    name: authorization
    type: apiKey
swagger: "2.0"
